name: Release
on:
  release:
    types: [created]

permissions:
  contents: write # Required for pushing docs
  id-token: write # Required for provenance
  packages: write # Required for publishing to github packages

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: '@eurocamp'

      - name: Install dependencies
        run: npm ci

      - name: Publish package release
        if: "!github.event.release.prerelease"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package pre-release
        if: "github.event.release.prerelease"
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
